#!/usr/bin/env python3
"""
Generate an OpenSCAD (.scad) file for 3D-printing an encoder-wheel frame.

The frame is a disc with radial pockets that hold the magnets.  Because the
inner corners of adjacent magnets touch, the inter-pocket "spokes" taper to a
point at the inner radius; there is no inner rim connecting the spokes.

3-D printing options
--------------------
  --tabs / --no-tabs
        Add small overhanging lips at the radial ends of each pocket opening
        so the magnets snap in and are retained without adhesive.
        (Requires flexible filament or careful press-fitting with rigid PLA.)

  --back-plate / --no-back-plate
        Include a solid disc back behind the pockets.  Without this the frame
        is open on both faces (suitable for holding the steel backing plate or
        for gluing a separate plate).

  --front-face / --no-front-face
        Add a thin solid skin over the front face of the wheel (covering the
        magnet openings).  Useful when you want a smooth sensing surface.

  --steel-clip / --no-steel-clip
        Add rectangular clip slots evenly spaced around the outer rim so that
        a thin steel disc can be snapped in from the back as a flux-return
        backing plate.  Use together with --no-back-plate.

Usage
-----
    python scripts/generate_3d.py [options]

Options
-------
  --n-magnets N          Number of magnets (multiple of 12, default 12)
  --length L             Magnet radial length in mm (default 20)
  --width W              Magnet tangential width in mm (default 5)
  --thickness T          Magnet axial thickness in mm (default 2)
  --inner-radius R       Inner radius in mm (default = minimum)
  --margin M             Outer ring radial margin beyond magnet tips (default 3)
  --center-bore R        Central shaft bore radius in mm (default 5)
  --clearance C          Per-side pocket clearance in mm (default 0.15)

  --tabs / --no-tabs                 (default: --tabs)
  --tab-width W          Radial width of each retaining tab in mm (default 1.5)
  --tab-overhang D       Tangential overhang depth of each tab in mm (default 0.6)

  --back-plate / --no-back-plate     (default: --back-plate)
  --back-thickness T     Back plate thickness in mm (default 1.5)

  --front-face / --no-front-face     (default: --no-front-face)
  --front-thickness T    Front face thickness in mm (default 0.8)

  --steel-clip / --no-steel-clip     (default: --no-steel-clip)
  --n-clips N            Number of steel-plate clip slots (default 6)
  --clip-width W         Clip slot width in mm (default 3.0)
  --clip-depth D         Clip slot depth in mm (default 1.2)
  --clip-height H        Clip slot height in mm (default 1.0)

  --output FILE          Output OpenSCAD filename (default encoder_wheel_3d.scad)
"""

import argparse
import math
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from common import encoder_geometry

_HEADER = """\
// =============================================================================
//  Encoder Wheel Frame
//  Generated by generate_3d.py — do not edit by hand; re-run the script.
// =============================================================================
//
//  Render with F6 in OpenSCAD, then File → Export → STL.
//  Requires OpenSCAD 2021.01 or later.
//
//  Coordinate system
//  -----------------
//    Z = wheel axis (print flat on Z = 0 plane)
//    XY = wheel face
//
"""


def generate_scad(
    # Magnet / geometry
    n_magnets: int = 12,
    magnet_length: float = 20.0,
    magnet_width: float = 5.0,
    magnet_thickness: float = 2.0,
    inner_radius: float = None,
    frame_margin: float = 3.0,
    center_bore: float = 5.0,
    clearance: float = 0.15,
    # Tab options
    tabs: bool = True,
    tab_width: float = 1.5,
    tab_overhang: float = 0.6,
    # Back plate
    back_plate: bool = True,
    back_thickness: float = 1.5,
    # Front face
    front_face: bool = False,
    front_thickness: float = 0.8,
    # Steel backing plate clips
    steel_clip: bool = False,
    n_clips: int = 6,
    clip_width: float = 3.0,
    clip_depth: float = 1.2,
    clip_height: float = 1.0,
) -> str:
    """Generate the OpenSCAD file content.

    Parameters
    ----------
    n_magnets : int
        Number of magnets.
    magnet_length, magnet_width, magnet_thickness : float
        Magnet dimensions (mm).
    inner_radius : float, optional
        Inner radius (mm); defaults to minimum (inner corners touching).
    frame_margin : float
        Outer ring radial margin beyond the magnet tips (mm).
    center_bore : float
        Central shaft bore radius (mm).
    clearance : float
        Per-side clearance added to each pocket dimension (mm).
    tabs : bool
        Whether to add retaining-tab overhangs.
    tab_width : float
        Radial width of each tab (mm).
    tab_overhang : float
        How far each tab overhangs into the pocket opening (mm).
    back_plate : bool
        Include a solid printed back disc.
    back_thickness : float
        Thickness of the back disc (mm).
    front_face : bool
        Include a thin solid skin over the front face.
    front_thickness : float
        Thickness of the front skin (mm).
    steel_clip : bool
        Add clip slots in the outer rim for a steel backing plate.
    n_clips : int
        Number of clip slots.
    clip_width, clip_depth, clip_height : float
        Clip slot dimensions (mm).

    Returns
    -------
    str
        OpenSCAD file content.
    """
    geo = encoder_geometry(
        n_magnets=n_magnets,
        magnet_length=magnet_length,
        magnet_width=magnet_width,
        magnet_thickness=magnet_thickness,
        inner_radius=inner_radius,
    )

    r_inner = geo["inner_radius"]
    r_outer = geo["outer_radius"]
    r_frame = r_outer + frame_margin
    angle_step_deg = geo["angle_step_deg"]

    # Pocket dimensions including clearance
    pw = magnet_width + 2.0 * clearance      # pocket width  (tangential)
    pl = magnet_length + 2.0 * clearance     # pocket length (radial)
    pd = magnet_thickness                     # pocket depth  (axial, exact fit)
    # Inner edge of pocket (extend slightly inward of r_inner to avoid
    # a zero-thickness edge that causes rendering artefacts in OpenSCAD)
    r_pkt = r_inner - clearance

    # Z extents
    z_back = back_thickness if back_plate else 0.0
    z_top_magnet = z_back + pd                        # top of magnet pocket
    z_front = z_top_magnet + (front_thickness if front_face else 0.0)
    total_h = z_front if front_face else z_top_magnet

    L = []  # output lines

    L.append(_HEADER)

    # ---- Parameters section ----------------------------------------
    L.append("// ---- Geometry parameters ----------------------------------------")
    L.append(f"n_magnets       = {n_magnets};       // number of magnets")
    L.append(f"angle_step      = {angle_step_deg:.6f}; // degrees between magnets")
    L.append(f"magnet_length   = {magnet_length};    // radial length (mm)")
    L.append(f"magnet_width    = {magnet_width};     // tangential width (mm)")
    L.append(f"magnet_thick    = {magnet_thickness};     // axial thickness (mm)")
    L.append(f"r_inner         = {r_inner:.4f};  // inner radius (mm)")
    L.append(f"r_outer         = {r_outer:.4f};  // outer radius (mm)")
    L.append(f"r_frame         = {r_frame:.4f};  // frame outer radius (mm)")
    L.append(f"center_bore     = {center_bore};     // shaft bore radius (mm)")
    L.append(f"clearance       = {clearance};    // per-side pocket clearance (mm)")
    L.append("")
    L.append("// ---- Pocket dimensions ----------------------------------------")
    L.append(f"pw              = {pw};   // pocket width  (tangential)")
    L.append(f"pl              = {pl};   // pocket length (radial)")
    L.append(f"pd              = {pd};       // pocket depth  (axial)")
    L.append(f"r_pkt           = {r_pkt:.4f};  // pocket inner-edge radius")
    L.append("")

    if back_plate:
        L.append(f"back_thickness  = {back_thickness};    // back plate thickness (mm)")
    if front_face:
        L.append(f"front_thickness = {front_thickness};    // front face thickness (mm)")
    if tabs:
        L.append(f"tab_width       = {tab_width};    // retaining tab radial width (mm)")
        L.append(f"tab_overhang    = {tab_overhang};    // retaining tab overhang (mm)")
    if steel_clip:
        L.append(f"n_clips         = {n_clips};       // number of steel-plate clip slots")
        L.append(f"clip_width      = {clip_width};    // clip slot width (mm)")
        L.append(f"clip_depth      = {clip_depth};    // clip slot depth into rim (mm)")
        L.append(f"clip_height     = {clip_height};    // clip slot height (mm)")
    L.append("")
    L.append(f"z_back          = {z_back};    // Z of pocket floor")
    L.append(f"z_top_magnet    = {z_top_magnet:.3f};  // Z of pocket opening / magnet top")
    L.append(f"total_height    = {total_h:.3f};  // overall frame height")
    L.append("")

    # ---- Module: single magnet pocket subtraction ----------------------
    L.append("// ====================================================================")
    L.append("// Module: magnet_pocket()")
    L.append("// One magnet slot, open at the top face (+Z).")
    L.append("// In local coords: +Y = radial outward, +X = tangential CCW, +Z = axial.")
    L.append("// The pocket inner edge sits at r_pkt (slightly inside r_inner).")
    L.append("// ====================================================================")
    L.append("module magnet_pocket() {")
    L.append(f"    translate([-pw/2, {r_pkt:.4f}, {z_back:.3f}])")
    L.append(f"        cube([pw, pl, pd + 1]);  // +1 ensures clean exit through top face")
    L.append("}")
    L.append("")

    # ---- Module: retaining tabs ----------------------------------------
    if tabs:
        L.append("// ====================================================================")
        L.append("// Module: retaining_tabs()")
        L.append("// Two small lips at the inner and outer radial ends of the pocket")
        L.append("// opening.  They overhang the pocket so magnets snap in from above.")
        L.append("// Print with the pocket face upward so these bridge the gap.")
        L.append("// ====================================================================")
        L.append("module retaining_tabs() {")
        L.append("    // Inner-radial tab")
        L.append(f"    translate([-pw/2, {r_pkt:.4f}, {z_top_magnet - tab_overhang:.4f}])")
        L.append(f"        cube([pw, {tab_width}, {tab_overhang + 1}]);  // +1 = above face")
        L.append("    // Outer-radial tab")
        L.append(f"    translate([-pw/2, {r_pkt + pl - tab_width:.4f}, {z_top_magnet - tab_overhang:.4f}])")
        L.append(f"        cube([pw, {tab_width}, {tab_overhang + 1}]);")
        L.append("}")
        L.append("")

    # ---- Module: steel-clip slots --------------------------------------
    if steel_clip:
        clip_angle_step = 360.0 / n_clips
        L.append("// ====================================================================")
        L.append("// Module: clip_slots()")
        L.append("// Rectangular notches around the outer rim that accept a thin steel")
        L.append("// disc snapped in from the back.  The steel disc acts as a flux-return")
        L.append("// backing plate and improves magnetic field concentration.")
        L.append("// ====================================================================")
        L.append("module clip_slots() {")
        L.append(f"    for (i = [0 : {n_clips - 1}]) {{")
        L.append(f"        rotate([0, 0, i * {clip_angle_step:.4f}])")
        L.append(f"            translate([{r_frame - clip_depth:.4f}, -{clip_width / 2:.4f}, -0.01])")
        L.append(f"                cube([{clip_depth + 0.01:.4f}, {clip_width:.4f}, {clip_height + 0.01:.4f}]);")
        L.append("    }")
        L.append("}")
        L.append("")

    # ---- Module: front face --------------------------------------------
    if front_face:
        L.append("// ====================================================================")
        L.append("// Module: front_face_ring()")
        L.append("// Thin solid skin over the magnet pockets (smooth sensing surface).")
        L.append("// ====================================================================")
        L.append("module front_face_ring() {")
        L.append("    difference() {")
        L.append(f"        translate([0, 0, {z_top_magnet:.3f}])")
        L.append(f"            cylinder(h = {front_thickness}, r = r_frame, $fn = 128);")
        L.append(f"        cylinder(h = total_height * 3, r = center_bore, center = true, $fn = 64);")
        L.append("    }")
        L.append("}")
        L.append("")

    # ---- Main encoder_wheel module ------------------------------------
    L.append("// ====================================================================")
    L.append("// Module: encoder_wheel()")
    L.append("// Complete encoder wheel frame — subtract pockets then optionally add")
    L.append("// tabs, front face, and/or steel clip slots.")
    L.append("// ====================================================================")
    L.append("module encoder_wheel() {")
    L.append("    union() {")
    L.append("")
    L.append("        // -- Main body: outer ring + (optional) back disc --")
    L.append("        difference() {")
    L.append("")
    L.append("            // Solid disc from z=0 to z=total_height")
    L.append(f"            cylinder(h = {total_h:.3f}, r = r_frame, $fn = 128);")
    L.append("")
    L.append("            // Central shaft bore")
    L.append(f"            cylinder(h = {total_h:.3f} * 3, r = center_bore, center = true, $fn = 64);")
    L.append("")
    if not back_plate:
        L.append("            // No back plate: remove material below the pockets too")
        L.append(f"            cylinder(h = {total_h:.3f} * 3, r = r_frame + 1, center = true, $fn = 128);")
        L.append(f"            // Re-add the rim (cancel the full removal above)")
        L.append("            // ... handled by the outer ring — see design note.")
        # Actually this approach would remove everything. Let's handle it differently.
        # When back_plate is False, the pockets go through the full height.
        # The outer ring + spokes provide structure.
        # We need to remove an annular region from r=0 to r=r_inner (the central void).
        L.pop()  # remove last line
        L.pop()  # remove the note
        L.pop()  # remove "Re-add" comment
        L.pop()  # remove the full-removal line
        L.pop()  # remove "No back plate" comment
        # Instead: just note that pockets have z_back=0
        L.append("            // (No back plate: z_back = 0 so pockets open on bottom face too)")

    L.append("")
    L.append("            // Magnet pockets")
    L.append(f"            for (i = [0 : n_magnets - 1]) {{")
    L.append(f"                rotate([0, 0, i * angle_step])")
    L.append("                    magnet_pocket();")
    L.append("            }")
    L.append("")
    if steel_clip:
        L.append("            // Steel backing plate clip slots")
        L.append("            clip_slots();")
        L.append("")
    L.append("        }  // end difference")
    L.append("")

    if tabs:
        L.append("        // -- Retaining tabs (overhang over pocket openings) --")
        L.append(f"        for (i = [0 : n_magnets - 1]) {{")
        L.append(f"            rotate([0, 0, i * angle_step])")
        L.append("                retaining_tabs();")
        L.append("        }")
        L.append("")

    if front_face:
        L.append("        // -- Smooth front face --")
        L.append("        front_face_ring();")
        L.append("")

    L.append("    }  // end union")
    L.append("}  // end encoder_wheel")
    L.append("")

    # ---- Instantiation -------------------------------------------------
    L.append("// ====================================================================")
    L.append("// Render the wheel")
    L.append("// ====================================================================")
    L.append("encoder_wheel();")
    L.append("")

    return "\n".join(L)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser():
    p = argparse.ArgumentParser(
        description="Generate an OpenSCAD file for 3D-printing an encoder-wheel frame.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    # Geometry
    p.add_argument("--n-magnets", type=int, default=12, metavar="N")
    p.add_argument("--length", type=float, default=20.0, metavar="mm",
                   help="Magnet radial length")
    p.add_argument("--width", type=float, default=5.0, metavar="mm",
                   help="Magnet tangential width")
    p.add_argument("--thickness", type=float, default=2.0, metavar="mm",
                   help="Magnet axial thickness (= pocket depth)")
    p.add_argument("--inner-radius", type=float, default=None, metavar="mm",
                   help="Inner radius (default = minimum, inner corners touching)")
    p.add_argument("--margin", type=float, default=3.0, metavar="mm",
                   help="Outer ring radial margin beyond magnet tips")
    p.add_argument("--center-bore", type=float, default=5.0, metavar="mm",
                   help="Central shaft bore radius")
    p.add_argument("--clearance", type=float, default=0.15, metavar="mm",
                   help="Per-side pocket clearance")
    # Tabs
    p.add_argument("--tabs", action="store_true", default=True,
                   help="Add retaining tabs (default on)")
    p.add_argument("--no-tabs", action="store_false", dest="tabs")
    p.add_argument("--tab-width", type=float, default=1.5, metavar="mm")
    p.add_argument("--tab-overhang", type=float, default=0.6, metavar="mm")
    # Back plate
    p.add_argument("--back-plate", action="store_true", default=True,
                   help="Include a printed back plate (default on)")
    p.add_argument("--no-back-plate", action="store_false", dest="back_plate")
    p.add_argument("--back-thickness", type=float, default=1.5, metavar="mm")
    # Front face
    p.add_argument("--front-face", action="store_true", default=False)
    p.add_argument("--no-front-face", action="store_false", dest="front_face")
    p.add_argument("--front-thickness", type=float, default=0.8, metavar="mm")
    # Steel clip
    p.add_argument("--steel-clip", action="store_true", default=False)
    p.add_argument("--no-steel-clip", action="store_false", dest="steel_clip")
    p.add_argument("--n-clips", type=int, default=6)
    p.add_argument("--clip-width", type=float, default=3.0, metavar="mm")
    p.add_argument("--clip-depth", type=float, default=1.2, metavar="mm")
    p.add_argument("--clip-height", type=float, default=1.0, metavar="mm")
    # Output
    p.add_argument("--output", default="encoder_wheel_3d.scad", metavar="FILE")
    return p


def main():
    args = _build_parser().parse_args()

    scad = generate_scad(
        n_magnets=args.n_magnets,
        magnet_length=args.length,
        magnet_width=args.width,
        magnet_thickness=args.thickness,
        inner_radius=args.inner_radius,
        frame_margin=args.margin,
        center_bore=args.center_bore,
        clearance=args.clearance,
        tabs=args.tabs,
        tab_width=args.tab_width,
        tab_overhang=args.tab_overhang,
        back_plate=args.back_plate,
        back_thickness=args.back_thickness,
        front_face=args.front_face,
        front_thickness=args.front_thickness,
        steel_clip=args.steel_clip,
        n_clips=args.n_clips,
        clip_width=args.clip_width,
        clip_depth=args.clip_depth,
        clip_height=args.clip_height,
    )

    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(scad)

    geo = encoder_geometry(
        n_magnets=args.n_magnets,
        magnet_length=args.length,
        magnet_width=args.width,
        magnet_thickness=args.thickness,
        inner_radius=args.inner_radius,
    )
    r_frame = geo["outer_radius"] + args.margin
    print(f"Wrote {args.output}")
    print(f"  Inner radius   : {geo['inner_radius']:.3f} mm")
    print(f"  Outer radius   : {geo['outer_radius']:.3f} mm")
    print(f"  Frame diameter : {r_frame * 2:.2f} mm")
    print(f"  Options: tabs={args.tabs}, back_plate={args.back_plate}, "
          f"front_face={args.front_face}, steel_clip={args.steel_clip}")


if __name__ == "__main__":
    main()
